# Generated by Django 2.1 on 2019-08-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190803_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Projects/Sites/icons'),
        ),
    ]
