# Generated by Django 2.1 on 2019-08-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_site_icon_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
