# Generated by Django 2.1 on 2019-08-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190828_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Projects', max_length=20)),
                ('background_image', models.ImageField(upload_to='Site/ProjectPage/')),
            ],
        ),
    ]
