# Generated by Django 2.1 on 2019-11-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
