# Generated by Django 2.2.4 on 2019-08-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=14)),
                ('address_type', models.CharField(choices=[('p', 'Primary'), ('s', 'Secondary')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('logo1', models.ImageField(upload_to='Site/Homepage/Company/')),
                ('logo2', models.ImageField(upload_to='Site/Homepage/Company/')),
                ('favicon', models.ImageField(null=True, upload_to='Site/Homepage/Company/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
                ('bg', models.ImageField(upload_to='Site/Homepage/SliderImages/')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDoSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Site/Homepage/others')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUsCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='Site/Homepage/others')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
                ('why_choose_us_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='homepage.WhyChooseUsSection')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDoCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='Site/Homepage/others')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
                ('what_we_do_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='homepage.WhatWeDoSection')),
            ],
        ),
    ]
