# Generated by Django 2.2.4 on 2019-08-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_company_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='logo1',
            new_name='logo_dark',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='logo2',
            new_name='logo_light',
        ),
    ]
