# Generated by Django 2.2.4 on 2019-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190803_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color1',
            field=models.CharField(default='#ff5e15', max_length=7),
        ),
    ]
