# Generated by Django 2.2.4 on 2019-08-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20190803_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimages',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sliderimages',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
