# Generated by Django 2.2.4 on 2019-08-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20190803_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseuscards',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.FlatIconsClassName'),
        ),
    ]
