# Generated by Django 2.2.4 on 2019-08-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('homepage', '0013_auto_20190803_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
                ('projects', models.ManyToManyField(to='projects.Project')),
            ],
        ),
    ]
