# Generated by Django 2.1 on 2019-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_footer_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonModelClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
    ]
