# Generated by Django 2.1 on 2019-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_commonmodelclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimages',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
