# Generated by Django 2.1 on 2019-10-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20191004_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimages',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
