# Generated by Django 2.1 on 2019-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20191004_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconHTMLTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=50)),
                ('html_tag', models.CharField(max_length=50)),
            ],
        ),
    ]
