# Generated by Django 2.1 on 2019-10-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_iconhtmltag'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedocards',
            name='icon_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.IconHTMLTag'),
        ),
    ]
