# Generated by Django 2.1 on 2019-10-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_auto_20191028_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentprojects',
            options={'ordering': ('order', 'title')},
        ),
        migrations.AlterModelOptions(
            name='sliderimages',
            options={'ordering': ('order', 'title')},
        ),
        migrations.AlterModelOptions(
            name='whatwedocards',
            options={'ordering': ('order', 'title')},
        ),
        migrations.AlterModelOptions(
            name='whychooseuscards',
            options={'ordering': ('order', 'title')},
        ),
        migrations.AddField(
            model_name='sliderimages',
            name='order',
            field=models.IntegerField(default=1000),
        ),
    ]
