# Generated by Django 2.1 on 2019-10-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_auto_20191028_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedocards',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
