# Generated by Django 2.1 on 2019-10-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_auto_20191028_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseuscards',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
