# Generated by Django 2.1 on 2019-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_auto_20191028_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentprojects',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
