# Generated by Django 2.1 on 2019-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_auto_20191029_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='menu_1_links',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_1_links', to='homepage.FooterLink'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='menu_1_title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='menu_2_links',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_2_links', to='homepage.FooterLink'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='menu_2_title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='menu_3_links',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_3_links', to='homepage.FooterLink'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='menu_3_title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
