# Generated by Django 2.1 on 2019-08-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_auto_20190819_0018'),
        ('homepage', '0016_commonmodelclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('commonmodelclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.CommonModelClasses')),
                ('title', models.CharField(default='About Us', max_length=20)),
                ('background_image', models.ImageField(upload_to='Site/AboutUs/')),
            ],
            bases=('homepage.commonmodelclasses',),
        ),
        migrations.CreateModel(
            name='OurTeamSection',
            fields=[
                ('commonmodelclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.CommonModelClasses')),
                ('title', models.CharField(default='Our Team', max_length=50)),
                ('sub_title', models.CharField(blank=True, default='We have a Good and Expert Team', max_length=100, null=True)),
            ],
            bases=('homepage.commonmodelclasses',),
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('commonmodelclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.CommonModelClasses')),
                ('name', models.CharField(max_length=80)),
                ('profile_picture', models.ImageField(upload_to='Site/AboutUs/Team/')),
            ],
            bases=('homepage.commonmodelclasses',),
        ),
        migrations.CreateModel(
            name='TeamMemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teammember',
            name='other_roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_roles', to='about_us.TeamMemberRole'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='primary_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_role', to='about_us.TeamMemberRole'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='about_us.OurTeamSection'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='about_us.TeamMember'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Site'),
        ),
    ]
