# Generated by Django 2.1 on 2019-08-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0016_commonmodelclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('commonmodelclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.CommonModelClasses')),
                ('title', models.CharField(default='About Us', max_length=20)),
                ('background_image', models.ImageField(upload_to='Site/AboutUs/')),
            ],
            bases=('homepage.commonmodelclasses',),
        ),
        migrations.CreateModel(
            name='OurTeamSection',
            fields=[
                ('commonmodelclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.CommonModelClasses')),
                ('title', models.CharField(default='Our Team', max_length=50)),
                ('sub_title', models.CharField(blank=True, default='We have a Good and Expert Team', max_length=100, null=True)),
            ],
            bases=('homepage.commonmodelclasses',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('commonmodelclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.CommonModelClasses')),
                ('name', models.CharField(max_length=80)),
                ('profile_picture', models.ImageField(upload_to='Site/AboutUs/Team/')),
            ],
            bases=('homepage.commonmodelclasses',),
        ),
        migrations.CreateModel(
            name='TeamMemberRole',
            fields=[
                ('commonmodelclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.CommonModelClasses')),
                ('role_name', models.CharField(max_length=100)),
            ],
            bases=('homepage.commonmodelclasses',),
        ),
        migrations.AddField(
            model_name='teammember',
            name='primary_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about_us.TeamMemberRole'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about_us.OurTeamSection'),
        ),
    ]
