# Generated by Django 2.1 on 2019-08-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='other_roles',
            field=models.ManyToManyField(related_name='other_roles', to='about_us.TeamMemberRole'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='primary_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_role', to='about_us.TeamMemberRole'),
        ),
    ]
