# Generated by Django 2.1 on 2019-08-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='other_roles',
            field=models.ManyToManyField(blank=True, related_name='other_roles', to='about_us.TeamMemberRole'),
        ),
    ]
