# Generated by Django 2.1 on 2019-08-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_commonmodelclasses'),
        ('projects', '0002_auto_20190803_0501'),
        ('about_us', '0002_auto_20190818_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('commonmodelclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.CommonModelClasses')),
                ('link', models.CharField(max_length=100)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Site')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='about_us.TeamMember')),
            ],
            bases=('homepage.commonmodelclasses',),
        ),
    ]
