# Generated by Django 2.1 on 2019-08-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_commonmodelclasses'),
        ('projects', '0002_auto_20190803_0501'),
        ('about_us', '0003_socialmedialinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMediaLinks',
            new_name='SocialMediaLink',
        ),
    ]
