# Generated by Django 2.1 on 2019-11-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_teammember_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
