# Generated by Django 2.1 on 2019-08-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_auto_20190819_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='media',
            new_name='site',
        ),
    ]
