# Generated by Django 2.1 on 2019-11-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliationpage',
            name='background_image',
            field=models.ImageField(upload_to='Site/AffiliationsPage/'),
        ),
        migrations.AlterField(
            model_name='affiliationpage',
            name='title',
            field=models.CharField(default='Affiliations', max_length=20),
        ),
    ]
