# Generated by Django 2.1 on 2019-11-22 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_album_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover_image',
            new_name='cover_image_url',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
